nodeExporter:
  enabled: false

grafana:
  enabled: true

  persistence:
    enabled: true
    type: pvc
    storageClassName: hostpath
    accessModes:
      - ReadWriteOnce
    size: 2Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 768Mi
prometheus:
  enabled: true

  prometheusSpec:
    retention: 7d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: hostpath
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

alertmanager:
  enabled: true

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: hostpath
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi