version: 0.2

phases:
  build:
    commands:
      - echo "Starting PayLater CodeBuild"
      - cd "Fronted+Backend(Paylater)"
      - echo "Inside PayLater directory"
      - pwd
      - ls -la
      - test -f go.work
      - test -f docker-compose.yml
      - echo "PayLater source validation successful"
