// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package sqlc

import (
	"context"
)

const createAdmin = `-- name: CreateAdmin :exec
INSERT INTO admins (
    admin_name,
    email,
    password,
    role
)
VALUES (?, ?, ?, ?)
`

type CreateAdminParams struct {
	AdminName string     `json:"admin_name"`
	Email     string     `json:"email"`
	Password  string     `json:"password"`
	Role      AdminsRole `json:"role"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) error {
	_, err := q.db.ExecContext(ctx, createAdmin,
		arg.AdminName,
		arg.Email,
		arg.Password,
		arg.Role,
	)
	return err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM admins
WHERE id = ?
`

func (q *Queries) DeleteAdmin(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAdmin, id)
	return err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, admin_name, email, password, role
FROM admins
WHERE email = ?
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.AdminName,
		&i.Email,
		&i.Password,
		&i.Role,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, admin_name, email, password, role
FROM admins
WHERE id = ?
`

func (q *Queries) GetAdminByID(ctx context.Context, id int32) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.AdminName,
		&i.Email,
		&i.Password,
		&i.Role,
	)
	return i, err
}

const getAllAdmins = `-- name: GetAllAdmins :many
SELECT id, admin_name, email, password, role
FROM admins
ORDER BY id
`

func (q *Queries) GetAllAdmins(ctx context.Context) ([]Admin, error) {
	rows, err := q.db.QueryContext(ctx, getAllAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Admin
	for rows.Next() {
		var i Admin
		if err := rows.Scan(
			&i.ID,
			&i.AdminName,
			&i.Email,
			&i.Password,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
