// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Merchant struct {
	ID                   int32          `json:"id"`
	MerchantName         string         `json:"merchant_name"`
	PhoneNumber          sql.NullString `json:"phone_number"`
	CommissionPercentage string         `json:"commission_percentage"`
}

type Transaction struct {
	ID                   int32        `json:"id"`
	UserID               int32        `json:"user_id"`
	MerchantID           int32        `json:"merchant_id"`
	Amount               string       `json:"amount"`
	Commission           string       `json:"commission"`
	CommissionPercentage string       `json:"commission_percentage"`
	TransactionDate      sql.NullTime `json:"transaction_date"`
}

type User struct {
	ID          int32  `json:"id"`
	UserName    string `json:"user_name"`
	Email       string `json:"email"`
	CreditLimit string `json:"credit_limit"`
	CurrentDue  string `json:"current_due"`
}
