// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getCustomersWithDue = `-- name: GetCustomersWithDue :many
SELECT id, user_name, email, password, role, credit_limit, current_due FROM users WHERE current_due > 0 ORDER BY current_due DESC
`

func (q *Queries) GetCustomersWithDue(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getCustomersWithDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.CreditLimit,
			&i.CurrentDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMerchantFeeCollected = `-- name: GetMerchantFeeCollected :one
SELECT SUM(commission) AS total_fee FROM transactions WHERE merchant_id = ?
`

func (q *Queries) GetMerchantFeeCollected(ctx context.Context, merchantID sql.NullInt32) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMerchantFeeCollected, merchantID)
	var total_fee interface{}
	err := row.Scan(&total_fee)
	return total_fee, err
}

const getTotalUserDue = `-- name: GetTotalUserDue :one
SELECT SUM(current_due) AS total_due FROM users
`

func (q *Queries) GetTotalUserDue(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalUserDue)
	var total_due interface{}
	err := row.Scan(&total_due)
	return total_due, err
}

const getUserDue = `-- name: GetUserDue :one
SELECT current_due FROM users WHERE id = ?
`

func (q *Queries) GetUserDue(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserDue, id)
	var current_due string
	err := row.Scan(&current_due)
	return current_due, err
}

const getUsersReachedCreditLimit = `-- name: GetUsersReachedCreditLimit :many
SELECT id, user_name, email, password, role, credit_limit, current_due FROM users WHERE current_due >= credit_limit
`

func (q *Queries) GetUsersReachedCreditLimit(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersReachedCreditLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.CreditLimit,
			&i.CurrentDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
