// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTransaction = `-- name: CreateTransaction :exec
Insert into transactions (user_id, merchant_id, transaction_type, amount, commission,commission_percentage) values (?,?,?,?,?,?)
`

type CreateTransactionParams struct {
	UserID               int32                       `json:"user_id"`
	MerchantID           sql.NullInt32               `json:"merchant_id"`
	TransactionType      TransactionsTransactionType `json:"transaction_type"`
	Amount               string                      `json:"amount"`
	Commission           string                      `json:"commission"`
	CommissionPercentage string                      `json:"commission_percentage"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createTransaction,
		arg.UserID,
		arg.MerchantID,
		arg.TransactionType,
		arg.Amount,
		arg.Commission,
		arg.CommissionPercentage,
	)
	return err
}

const getAllTransactions = `-- name: GetAllTransactions :many
Select id, user_id, merchant_id, transaction_type, amount, commission, commission_percentage from transactions
`

func (q *Queries) GetAllTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getAllTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantID,
			&i.TransactionType,
			&i.Amount,
			&i.Commission,
			&i.CommissionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
Select id, user_id, merchant_id, transaction_type, amount, commission, commission_percentage from transactions where id = ?
`

func (q *Queries) GetTransactionByID(ctx context.Context, id int32) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantID,
		&i.TransactionType,
		&i.Amount,
		&i.Commission,
		&i.CommissionPercentage,
	)
	return i, err
}

const getTransactionsByMerchant = `-- name: GetTransactionsByMerchant :many
SELECT id, user_id, merchant_id, transaction_type, amount, commission, commission_percentage FROM transactions WHERE merchant_id = ?
`

func (q *Queries) GetTransactionsByMerchant(ctx context.Context, merchantID sql.NullInt32) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantID,
			&i.TransactionType,
			&i.Amount,
			&i.Commission,
			&i.CommissionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByUser = `-- name: GetTransactionsByUser :many
SELECT id, user_id, merchant_id, transaction_type, amount, commission, commission_percentage FROM transactions WHERE user_id = ?
`

func (q *Queries) GetTransactionsByUser(ctx context.Context, userID int32) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantID,
			&i.TransactionType,
			&i.Amount,
			&i.Commission,
			&i.CommissionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
