// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (user_name, email,password ,role)VALUES (?, ?,?,?)
`

type CreateUserParams struct {
	UserName string    `json:"user_name"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
	Role     UsersRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.UserName,
		arg.Email,
		arg.Password,
		arg.Role,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, user_name, email, password, role, credit_limit, current_due FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.CreditLimit,
			&i.CurrentDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, user_name, email, password, role, credit_limit, current_due
FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreditLimit,
		&i.CurrentDue,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, user_name, email, password, role, credit_limit, current_due FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreditLimit,
		&i.CurrentDue,
	)
	return i, err
}

const updateCurrentDue = `-- name: UpdateCurrentDue :exec
UPDATE users
SET current_due = ?
WHERE id = ?
`

type UpdateCurrentDueParams struct {
	CurrentDue string `json:"current_due"`
	ID         int32  `json:"id"`
}

func (q *Queries) UpdateCurrentDue(ctx context.Context, arg UpdateCurrentDueParams) error {
	_, err := q.db.ExecContext(ctx, updateCurrentDue, arg.CurrentDue, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET user_name = ?, email = ? WHERE id = ?
`

type UpdateUserParams struct {
	UserName string `json:"user_name"`
	Email    string `json:"email"`
	ID       int32  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.UserName, arg.Email, arg.ID)
	return err
}
