// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Merchant struct {
	ID                   int32          `json:"id"`
	MerchantName         string         `json:"merchant_name"`
	Email                string         `json:"email"`
	Password             string         `json:"password"`
	PhoneNumber          sql.NullString `json:"phone_number"`
	CommissionPercentage string         `json:"commission_percentage"`
}
