// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package sqlc

import (
	"context"
)

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT id, merchant_name, email, password, phone_number, commission_percentage
FROM merchants
WHERE id = ?
`

func (q *Queries) GetMerchantByID(ctx context.Context, id int32) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByID, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.MerchantName,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.CommissionPercentage,
	)
	return i, err
}
