// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, user_name, email, password, credit_limit, current_due
FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.Password,
		&i.CreditLimit,
		&i.CurrentDue,
	)
	return i, err
}

const updateCurrentDue = `-- name: UpdateCurrentDue :exec
UPDATE users
SET current_due = ?
WHERE id = ?
`

type UpdateCurrentDueParams struct {
	CurrentDue string `json:"current_due"`
	ID         int32  `json:"id"`
}

func (q *Queries) UpdateCurrentDue(ctx context.Context, arg UpdateCurrentDueParams) error {
	_, err := q.db.ExecContext(ctx, updateCurrentDue, arg.CurrentDue, arg.ID)
	return err
}
