// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type User struct {
	ID          int32  `json:"id"`
	UserName    string `json:"user_name"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	CreditLimit string `json:"credit_limit"`
	CurrentDue  string `json:"current_due"`
}
