apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql
  namespace: paylater

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent

          securityContext:
            seccompProfile:
              type: RuntimeDefault

          ports:
            - containerPort: 3306
              protocol: TCP

          envFrom:
            - secretRef:
                name: mysql-secret

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD"
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 10

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD"
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

        - name: mysql-initdb
          configMap:
            name: mysql-initdb