// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
)

type AdminsRole string

const (
	AdminsRoleSUPERADMIN AdminsRole = "SUPER_ADMIN"
	AdminsRoleADMIN      AdminsRole = "ADMIN"
)

func (e *AdminsRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminsRole(s)
	case string:
		*e = AdminsRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminsRole: %T", src)
	}
	return nil
}

type NullAdminsRole struct {
	AdminsRole AdminsRole `json:"admins_role"`
	Valid      bool       `json:"valid"` // Valid is true if AdminsRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminsRole) Scan(value interface{}) error {
	if value == nil {
		ns.AdminsRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminsRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminsRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminsRole), nil
}

type Admin struct {
	ID        int32      `json:"id"`
	AdminName string     `json:"admin_name"`
	Email     string     `json:"email"`
	Password  string     `json:"password"`
	Role      AdminsRole `json:"role"`
}
