apiVersion: apps/v1
kind: Deployment

metadata:
  name: merchant
  namespace: paylater

spec:
  replicas: 1

  selector:
    matchLabels:
      app: merchant

  template:
    metadata:
      labels:
        app: merchant

    spec:
      containers:
        - name: merchant
          image: haripriyanka99/paylater-merchant:v2
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 9094

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          env:
            # Non-sensitive configuration from ConfigMap
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: paylater-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: paylater-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: paylater-config
                  key: DB_NAME

            # Sensitive configuration from Secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: merchant-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: merchant-secret
                  key: DB_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: merchant-secret
                  key: JWT_SECRET

            - name: INTERNAL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: merchant-secret
                  key: INTERNAL_SERVICE_TOKEN

          readinessProbe:
            httpGet:
              path: /health
              port: 9094
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 9094
            initialDelaySeconds: 30
            periodSeconds: 10