// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createMerchant = `-- name: CreateMerchant :exec
INSERT INTO merchants (
    merchant_name,
    email,
    password,
    phone_number,
    commission_percentage
)
VALUES (?, ?, ?, ?, ?)
`

type CreateMerchantParams struct {
	MerchantName         string         `json:"merchant_name"`
	Email                string         `json:"email"`
	Password             string         `json:"password"`
	PhoneNumber          sql.NullString `json:"phone_number"`
	CommissionPercentage string         `json:"commission_percentage"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) error {
	_, err := q.db.ExecContext(ctx, createMerchant,
		arg.MerchantName,
		arg.Email,
		arg.Password,
		arg.PhoneNumber,
		arg.CommissionPercentage,
	)
	return err
}

const deleteMerchant = `-- name: DeleteMerchant :exec
DELETE FROM merchants
WHERE id = ?
`

func (q *Queries) DeleteMerchant(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMerchant, id)
	return err
}

const getAllMerchants = `-- name: GetAllMerchants :many
SELECT id, merchant_name, email, password, phone_number, commission_percentage
FROM merchants
`

func (q *Queries) GetAllMerchants(ctx context.Context) ([]Merchant, error) {
	rows, err := q.db.QueryContext(ctx, getAllMerchants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Merchant
	for rows.Next() {
		var i Merchant
		if err := rows.Scan(
			&i.ID,
			&i.MerchantName,
			&i.Email,
			&i.Password,
			&i.PhoneNumber,
			&i.CommissionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMerchantByEmail = `-- name: GetMerchantByEmail :one
SELECT id, merchant_name, email, password, phone_number, commission_percentage
FROM merchants
WHERE email = ?
`

func (q *Queries) GetMerchantByEmail(ctx context.Context, email string) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByEmail, email)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.MerchantName,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.CommissionPercentage,
	)
	return i, err
}

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT id, merchant_name, email, password, phone_number, commission_percentage
FROM merchants
WHERE id = ?
`

func (q *Queries) GetMerchantByID(ctx context.Context, id int32) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByID, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.MerchantName,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.CommissionPercentage,
	)
	return i, err
}

const updateCommission = `-- name: UpdateCommission :exec
UPDATE merchants
SET commission_percentage = ?
WHERE id = ?
`

type UpdateCommissionParams struct {
	CommissionPercentage string `json:"commission_percentage"`
	ID                   int32  `json:"id"`
}

func (q *Queries) UpdateCommission(ctx context.Context, arg UpdateCommissionParams) error {
	_, err := q.db.ExecContext(ctx, updateCommission, arg.CommissionPercentage, arg.ID)
	return err
}

const updateMerchant = `-- name: UpdateMerchant :exec
UPDATE merchants
SET merchant_name = ?, phone_number = ?
WHERE id = ?
`

type UpdateMerchantParams struct {
	MerchantName string         `json:"merchant_name"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	ID           int32          `json:"id"`
}

func (q *Queries) UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) error {
	_, err := q.db.ExecContext(ctx, updateMerchant, arg.MerchantName, arg.PhoneNumber, arg.ID)
	return err
}
