// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employee.sql

package db

import (
	"context"
)

const createEmployee = `-- name: CreateEmployee :exec
INSERT INTO emp1 (
    name,
    age,
    salary
)
VALUES (?, ?, ?)
`

type CreateEmployeeParams struct {
	Name   string
	Age    int32
	Salary string
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) error {
	_, err := q.db.ExecContext(ctx, createEmployee, arg.Name, arg.Age, arg.Salary)
	return err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM emp1
WHERE id = ?
`

func (q *Queries) DeleteEmployee(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteEmployee, id)
	return err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, name, age, salary
FROM emp1
WHERE id = ?
`

func (q *Queries) GetEmployee(ctx context.Context, id int32) (Emp1, error) {
	row := q.db.QueryRowContext(ctx, getEmployee, id)
	var i Emp1
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Age,
		&i.Salary,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, name, age, salary
FROM emp1
`

func (q *Queries) ListEmployees(ctx context.Context) ([]Emp1, error) {
	rows, err := q.db.QueryContext(ctx, listEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Emp1
	for rows.Next() {
		var i Emp1
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.Salary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :exec
UPDATE emp1
SET
    name = ?,
    age = ?,
    salary = ?
WHERE id = ?
`

type UpdateEmployeeParams struct {
	Name   string
	Age    int32
	Salary string
	ID     int32
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) error {
	_, err := q.db.ExecContext(ctx, updateEmployee,
		arg.Name,
		arg.Age,
		arg.Salary,
		arg.ID,
	)
	return err
}
