// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package db

import (
	"context"
)

const countPlayers = `-- name: CountPlayers :one
SELECT COUNT(*)
FROM people
`

func (q *Queries) CountPlayers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlayers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllPlayers = `-- name: GetAllPlayers :many
SELECT
    playerID,
    birthYear,
    birthMonth,
    birthDay,
    birthCountry,
    birthState,
    birthCity,
    deathYear,
    deathMonth,
    deathDay,
    deathCountry,
    deathState,
    deathCity,
    nameFirst,
    nameLast,
    nameGiven,
    weight,
    height,
    bats,
    throws,
    debut,
    finalGame,
    retroID,
    bbrefID
FROM people
ORDER BY playerID
LIMIT ?
OFFSET ?
`

type GetAllPlayersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllPlayers(ctx context.Context, arg GetAllPlayersParams) ([]Person, error) {
	rows, err := q.db.QueryContext(ctx, getAllPlayers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.Playerid,
			&i.Birthyear,
			&i.Birthmonth,
			&i.Birthday,
			&i.Birthcountry,
			&i.Birthstate,
			&i.Birthcity,
			&i.Deathyear,
			&i.Deathmonth,
			&i.Deathday,
			&i.Deathcountry,
			&i.Deathstate,
			&i.Deathcity,
			&i.Namefirst,
			&i.Namelast,
			&i.Namegiven,
			&i.Weight,
			&i.Height,
			&i.Bats,
			&i.Throws,
			&i.Debut,
			&i.Finalgame,
			&i.Retroid,
			&i.Bbrefid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT
    playerID,
    birthYear,
    birthMonth,
    birthDay,
    birthCountry,
    birthState,
    birthCity,
    deathYear,
    deathMonth,
    deathDay,
    deathCountry,
    deathState,
    deathCity,
    nameFirst,
    nameLast,
    nameGiven,
    weight,
    height,
    bats,
    throws,
    debut,
    finalGame,
    retroID,
    bbrefID
FROM people
WHERE playerID = ?
`

func (q *Queries) GetPlayerByID(ctx context.Context, playerid string) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByID, playerid)
	var i Person
	err := row.Scan(
		&i.Playerid,
		&i.Birthyear,
		&i.Birthmonth,
		&i.Birthday,
		&i.Birthcountry,
		&i.Birthstate,
		&i.Birthcity,
		&i.Deathyear,
		&i.Deathmonth,
		&i.Deathday,
		&i.Deathcountry,
		&i.Deathstate,
		&i.Deathcity,
		&i.Namefirst,
		&i.Namelast,
		&i.Namegiven,
		&i.Weight,
		&i.Height,
		&i.Bats,
		&i.Throws,
		&i.Debut,
		&i.Finalgame,
		&i.Retroid,
		&i.Bbrefid,
	)
	return i, err
}

const getPlayersByCursor = `-- name: GetPlayersByCursor :many
SELECT
    playerID,
    birthYear,
    birthMonth,
    birthDay,
    birthCountry,
    birthState,
    birthCity,
    deathYear,
    deathMonth,
    deathDay,
    deathCountry,
    deathState,
    deathCity,
    nameFirst,
    nameLast,
    nameGiven,
    weight,
    height,
    bats,
    throws,
    debut,
    finalGame,
    retroID,
    bbrefID
FROM people
WHERE playerID > ?
ORDER BY playerID
LIMIT ?
`

type GetPlayersByCursorParams struct {
	Playerid string
	Limit    int32
}

func (q *Queries) GetPlayersByCursor(ctx context.Context, arg GetPlayersByCursorParams) ([]Person, error) {
	rows, err := q.db.QueryContext(ctx, getPlayersByCursor, arg.Playerid, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.Playerid,
			&i.Birthyear,
			&i.Birthmonth,
			&i.Birthday,
			&i.Birthcountry,
			&i.Birthstate,
			&i.Birthcity,
			&i.Deathyear,
			&i.Deathmonth,
			&i.Deathday,
			&i.Deathcountry,
			&i.Deathstate,
			&i.Deathcity,
			&i.Namefirst,
			&i.Namelast,
			&i.Namegiven,
			&i.Weight,
			&i.Height,
			&i.Bats,
			&i.Throws,
			&i.Debut,
			&i.Finalgame,
			&i.Retroid,
			&i.Bbrefid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayersByName = `-- name: GetPlayersByName :many
SELECT
    playerid, birthyear, birthmonth, birthday, birthcountry, birthstate, birthcity, deathyear, deathmonth, deathday, deathcountry, deathstate, deathcity, namefirst, namelast, namegiven, weight, height, bats, throws, debut, finalgame, retroid, bbrefid
FROM people
WHERE
    LOWER(nameFirst) LIKE CONCAT('%', LOWER(?), '%')
    OR LOWER(nameLast) LIKE CONCAT('%', LOWER(?), '%')
    OR LOWER(nameGiven) LIKE CONCAT('%', LOWER(?), '%')
    OR LOWER(
        CONCAT(nameFirst, ' ', nameLast)
    ) LIKE CONCAT(
        '%',
        LOWER(?),
        '%'
    )
    OR LOWER(
        REPLACE(
            CONCAT(nameFirst, nameLast),
            ' ',
            ''
        )
    ) LIKE CONCAT(
        '%',
        REPLACE(LOWER(?), ' ', ''),
        '%'
    )
ORDER BY nameLast, nameFirst
`

type GetPlayersByNameParams struct {
	Search string
}

func (q *Queries) GetPlayersByName(ctx context.Context, arg GetPlayersByNameParams) ([]Person, error) {
	rows, err := q.db.QueryContext(ctx, getPlayersByName,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.Playerid,
			&i.Birthyear,
			&i.Birthmonth,
			&i.Birthday,
			&i.Birthcountry,
			&i.Birthstate,
			&i.Birthcity,
			&i.Deathyear,
			&i.Deathmonth,
			&i.Deathday,
			&i.Deathcountry,
			&i.Deathstate,
			&i.Deathcity,
			&i.Namefirst,
			&i.Namelast,
			&i.Namegiven,
			&i.Weight,
			&i.Height,
			&i.Bats,
			&i.Throws,
			&i.Debut,
			&i.Finalgame,
			&i.Retroid,
			&i.Bbrefid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
